= TODO Application

== What is the todo applcation?
This application is a simple microservice application based on the link:https://thorntail.io/[Thorntail.io] framework for creating todo entries in a database via a simple web UI.
This example application is used for the docker training as an application we want to run in a Docker Container.

== How to build it?
The application can be build with the following command.
[source,bash]
----
mvn clean install
----
The microservice standalone artifact is the todo-<version>-thorntail.jar.

== Application dependencies
The application depends on an mysql database and expectes the following environment variables to be set.

* *DB_URL:* The jdbc url pointing to the mysql datbase
* *DB_USER:* The user for the authentication
* *DB_PASSWORD:* The password for the authentication

== How to run it?
The application can be started with the following command. +
[source,java]
----
java -jar todo-<version>-thorntail.jar \
   -Djava.net.preferIPv4Stack=true \
   -Dswarm.bind.address=0.0.0.0
----
