version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  web:
    image: adrianfarmadin/todo-jsf-example
    environment:
      - VIRTUAL_HOST=todo.127.0.0.1.xip.io
    depends_on:
     - db
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=super-secret-pw
      - MYSQL_DATABASE=todo 
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=todo
    volumes:
      - db-vol:/var/lib/mysql
  adminer:
    image: adminer
    environment:
      - VIRTUAL_HOST=adminer.127.0.0.1.xip.io

volumes:
  db-vol:
