= Docker training

This repository holds the sources for our base docker training, which is meant to introduce Docker and Docker Compose to
software developers. +

== Setup
Follow the appropriate link for or OS, to see how to install and setup Docker.

* link:./doc/01_setup_win.adoc[Docker on Windows Host with Windows-Subystem-Linux]

.Windows users
[IMPORTANT]
===============================
Some commands to not run natively under Windows. In those cases I have provided a working windows alternative. However, it is important that those commands are executed from within a PowerShell and not cmd.
===============================

* link:./doc/02_setup_virtualbox_ubuntu.adoc[Virtualbox Ubuntu VM]
* link:./doc/03_setup_vagrant.adoc[Vagrant Ubuntu VM]

== Sample applications
You find the sample applications at link:./apps[Sample Applications].

* link:./apps/todo[Todo Sample application] +
  A simple sample application used for showing how to run an app in a Docker Container

== Presentations
You find the presentations at link:./slides[Slides].

* link:./slides/intro[Intro] +
  The slides for the first steps with Docker and Docker Compose
